# **Numpy**

## **What is NumPy?**  
NumPy is a Python library used for working with arrays.  
It also has functions for working in domain of linear algebra, fourier transform, and matrices.

## **Why Use NumPy?**  
In Python we have lists that serve the purpose of arrays, but they are slow to process.  
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.  
The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with `ndarray` very easy.  
  
Arrays are very frequently used in data science, where speed and resources are very important.

## **Why is NumPy Faster Than Lists?**  
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.  

This behavior is called **`locality of reference`** in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## **Which Language is NumPy written in?**  
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

## **Setup numpy in application**  

In [2]:
import numpy as np

### **Checking NumPy Version**

In [3]:
print(np.__version__)

1.19.5


## **NumPy Creating Arrays**  
NumPy is used to work with arrays. The array object in NumPy is called ndarray.  
  
We can create a NumPy ndarray object by using the array() function.  
  
To create an ndarray, we can pass a `list, tuple or any array-like` object into the `array()` method, and it will be converted into an ndarray:

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


> `type()`: This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

## **Dimensions in Arrays**  
A dimension in arrays is one level of array depth (nested arrays).  
`nested array: are arrays that have arrays as their elements.`  

In [14]:
# 0-D Array
ZeroDimensionalArray = np.array(42)
print(ZeroDimensionalArray)
print('***********************')

# 1-D Array
oneDimensionalArray = np.array([1, 2, 3, 4, 5])
print(oneDimensionalArray)
print('***********************')

# 2-D Array
#NumPy has a whole sub module dedicated towards matrix operations called numpy.mat
twoDimensionalArray = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(twoDimensionalArray)
print('***********************')

# 3-D Array
threeDimensionalArray = np.array([[[0, 1, 2], [10, 11, 12]], [[20, 21, 22], [30, 31, 32]]])
print(threeDimensionalArray)
print('***********************')

42
***********************
[1 2 3 4 5]
***********************
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
***********************
[[[ 0  1  2]
  [10 11 12]]

 [[20 21 22]
  [30 31 32]]]
***********************


> **2D-Array: NumPy has a whole sub module dedicated towards matrix operations called `numpy.mat`**  
> **3D-Array: These are often used to represent a 3rd order tensor.**

## **Check Number of Dimensions?**  
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.  

In [8]:
print(ZeroDimensionalArray.ndim)
print(oneDimensionalArray.ndim)
print(twoDimensionalArray.ndim)
print(threeDimensionalArray.ndim)

0
1
2
3


## **Higher Dimensional Arrays**  
An array can have any number of dimensions.  
  
When the array is created, you can define the number of dimensions by using the **`ndmin`** argument.

In [10]:
multiDimensionalArray = np.array([1, 2, 3, 4], ndmin=5)

print(multiDimensionalArray)
print('Number of Dimensions :', multiDimensionalArray.ndim)

[[[[[1 2 3 4]]]]]
Number of Dimensions : 5


**In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the `vector`, the 3rd dim has 1 element that is the `matrix with the vector`, the 2nd dim has 1 element that is `3D array` and 1st dim has 1 element that is a `4D array`.**

## **NumPy Array Indexing**  
### **Access Array Elements**  
Array indexing is the same as accessing an array element.  
You can access an array element by referring to its index number.  
  
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [15]:
print('2nd element on 1st dim: ', twoDimensionalArray[0, 1])
print('5th element on 2nd dim: ', twoDimensionalArray[1, 4])

#Access the third element of the second array of the first array:
print(threeDimensionalArray[0, 1, 2])


2nd element on 1st dim:  2
5th element on 2nd dim:  10
12


**Example Explained**  
threeDimensionalArray = np.array([[[0, 1, 2], [10, 11, 12]], [[20, 21, 22], [30, 31, 32]]])  
arr[0, 1, 2] prints the value 12.  
  
And this is why:  
  
The first number represents the first dimension, which contains two arrays:  
[[0, 1, 2], [10, 11, 12]]  
and:  
[[20, 21, 22], [30, 31, 32]]  
Since we selected 0, we are left with the first array:  
[[0, 1, 2], [10, 11, 12]]  
  
The second number represents the second dimension, which also contains two arrays:  
[0, 1, 2]  
and:  
[10, 11, 12]  
Since we selected 1, we are left with the second array:  
[10, 11, 12]  
  
The third number represents the third dimension, which contains three values:  
10  
11  
12  
Since we selected 2, we end up with the third value:  
12  

### **Negative Indexing**  
Use negative indexing to access an array from the end.

In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## **NumPy Array Slicing**  
### **Slicing arrays**  
Slicing in python means taking elements from one given index to another given index.  
  
We pass slice instead of index like this: **`[start:end]`**.  
  
We can also define the step, like this: **`[start:end:step]`**.  
> **Note:** The result includes the start index, but excludes the end index.  
  
If we don't pass start its considered 0  
  
If we don't pass end its considered length of array in that dimension  
  
If we don't pass step its considered 1  